import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export function generateCanonicalBundle(): { fileCount: number; outputPath: string } {
  const migrationsDir = path.resolve(__dirname, '../migrations');
  const outputPath = path.resolve(__dirname, '../deploy_all_migrations.sql');

  const files = fs.readdirSync(migrationsDir)
    .filter(f => f.endsWith('.sql'))
    .sort();

  console.log(`📦 Bundling ${files.length} canonical migrations from ${migrationsDir}...`);

  const header = [
    '--',
    '-- =============================================================================',
    '-- AUTO-GENERATED CANONICAL MIGRATION BUNDLE',
    '-- DO NOT EDIT THIS FILE DIRECTLY. Generated from packages/supabase/migrations/',
    `-- Generated on: ${new Date().toISOString()}`,
    '-- =============================================================================',
    '--',
    '',
  ].join('\n');

  const contents: string[] = [header];

  for (const file of files) {
    const fullPath = path.join(migrationsDir, file);
    const rawContent = fs.readFileSync(fullPath, 'utf8');
    
    // Strip trailing whitespace per line to guarantee git diff --check passes
    const cleanedLines = rawContent.split(/\r?\n/).map(line => line.trimEnd());
    const cleanedContent = cleanedLines.join('\n').trim();

    contents.push(`\n-- >>> Migration: ${file} >>>\n`);
    contents.push(cleanedContent);
    contents.push(`\n-- <<< End of ${file} <<<\n`);
  }

  const finalSql = contents.join('\n') + '\n';
  fs.writeFileSync(outputPath, finalSql, 'utf8');

  console.log(`✅ Successfully generated ${outputPath} (${finalSql.split('\n').length} lines).`);
  return { fileCount: files.length, outputPath };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  generateCanonicalBundle();
}
